const daysAgo = (n) => {
  const date = new Date();
  date.setDate(date.getDate() - n);
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0"); // miesiące są 0-indexed
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
};

const initialState = {
  auth: {
    settings: { notifications: true, emailUpdates: true, locationAccess: false, saveHistory: true },
  },
  movies: {
    watched: [
      {
        Title: "Inception",
        Year: "2010",
        Rated: "PG-13",
        Released: "16 Jul 2010",
        Runtime: "148 min",
        Genre: "Action, Adventure, Sci-Fi",
        Director: "Christopher Nolan",
        Writer: "Christopher Nolan",
        Actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
        Plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
        Language: "English, Japanese, French",
        Country: "United States, United Kingdom",
        Awards: "Won 4 Oscars. 159 wins & 220 nominations total",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
        Ratings: [
          { Source: "Internet Movie Database", Value: "8.8/10" },
          { Source: "Rotten Tomatoes", Value: "87%" },
          { Source: "Metacritic", Value: "74/100" },
        ],
        Metascore: "74",
        imdbRating: "8.8",
        imdbVotes: "2,743,035",
        imdbID: "tt1375666",
        Type: "movie",
        DVD: "N/A",
        BoxOffice: "$292,587,330",
        Production: "N/A",
        Website: "N/A",
        Response: "True",
        rating: 9,
        notes: "Engaging plot with unexpected twists.",
        date: daysAgo(71),
      },
      {
        Title: "Interstellar",
        Year: "2014",
        Rated: "PG-13",
        Released: "07 Nov 2014",
        Runtime: "169 min",
        Genre: "Adventure, Drama, Sci-Fi",
        Director: "Christopher Nolan",
        Writer: "Jonathan Nolan, Christopher Nolan",
        Actors: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
        Plot: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
        Language: "English",
        Country: "United States, United Kingdom, Canada",
        Awards: "Won 1 Oscar. 44 wins & 148 nominations total",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_SX300.jpg",
        Ratings: [
          { Source: "Internet Movie Database", Value: "8.7/10" },
          { Source: "Rotten Tomatoes", Value: "73%" },
          { Source: "Metacritic", Value: "74/100" },
        ],
        Metascore: "74",
        imdbRating: "8.7",
        imdbVotes: "2,423,918",
        imdbID: "tt0816692",
        Type: "movie",
        DVD: "N/A",
        BoxOffice: "$203,227,580",
        Production: "N/A",
        Website: "N/A",
        Response: "True",
        rating: 10,
        notes: "masterpiece!",
        date: daysAgo(51),
      },
      {
        Title: "The Matrix",
        Year: "1999",
        Rated: "R",
        Released: "31 Mar 1999",
        Runtime: "136 min",
        Genre: "Action, Sci-Fi",
        Director: "Lana Wachowski, Lilly Wachowski",
        Writer: "Lilly Wachowski, Lana Wachowski",
        Actors: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
        Plot: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
        Language: "English",
        Country: "United States, Australia",
        Awards: "Won 4 Oscars. 42 wins & 52 nominations total",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_SX300.jpg",
        Ratings: [
          { Source: "Internet Movie Database", Value: "8.7/10" },
          { Source: "Rotten Tomatoes", Value: "83%" },
          { Source: "Metacritic", Value: "73/100" },
        ],
        Metascore: "73",
        imdbRating: "8.7",
        imdbVotes: "2,195,275",
        imdbID: "tt0133093",
        Type: "movie",
        DVD: "N/A",
        BoxOffice: "$172,076,928",
        Production: "N/A",
        Website: "N/A",
        Response: "True",
        rating: 10,
        notes: "a must-watch for anyone who loves sci-fi",
        date: daysAgo(43),
      },
      {
        Title: "Star Wars: Episode VI - Return of the Jedi",
        Year: "1983",
        Rated: "PG",
        Released: "25 May 1983",
        Runtime: "131 min",
        Genre: "Action, Adventure, Fantasy",
        Director: "Richard Marquand",
        Writer: "Lawrence Kasdan, George Lucas",
        Actors: "Mark Hamill, Harrison Ford, Carrie Fisher",
        Plot: "After rescuing Han Solo from Jabba the Hutt, the Rebel Alliance attempts to destroy the second Death Star while Luke struggles to help Darth Vader back from the dark side.",
        Language: "English, Kikuyu, Tagalog, Kalmyk-Oirat, Quechua, Polish",
        Country: "United States",
        Awards: "Nominated for 4 Oscars. 25 wins & 23 nominations total",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BNWEwOTI0MmUtMGNmNy00ODViLTlkZDQtZTg1YmQ3MDgyNTUzXkEyXkFqcGc@._V1_SX300.jpg",
        Ratings: [
          { Source: "Internet Movie Database", Value: "8.3/10" },
          { Source: "Rotten Tomatoes", Value: "83%" },
          { Source: "Metacritic", Value: "58/100" },
        ],
        Metascore: "58",
        imdbRating: "8.3",
        imdbVotes: "1,187,542",
        imdbID: "tt0086190",
        Type: "movie",
        DVD: "N/A",
        BoxOffice: "$316,566,101",
        Production: "N/A",
        Website: "N/A",
        Response: "True",
        rating: 8,
        notes: "",
        date: daysAgo(42),
      },
      {
        Title: "Game of Thrones",
        Year: "2011–2019",
        Rated: "TV-MA",
        Released: "17 Apr 2011",
        Runtime: "57 min",
        Genre: "Action, Adventure, Drama",
        Director: "N/A",
        Writer: "David Benioff, D.B. Weiss",
        Actors: "Emilia Clarke, Peter Dinklage, Kit Harington",
        Plot: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
        Language: "English",
        Country: "United States, United Kingdom",
        Awards: "Won 59 Primetime Emmys. 395 wins & 655 nominations total",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BMTNhMDJmNmYtNDQ5OS00ODdlLWE0ZDAtZTgyYTIwNDY3OTU3XkEyXkFqcGc@._V1_SX300.jpg",
        Ratings: [{ Source: "Internet Movie Database", Value: "9.2/10" }],
        Metascore: "N/A",
        imdbRating: "9.2",
        imdbVotes: "2,487,814",
        imdbID: "tt0944947",
        Type: "series",
        totalSeasons: "8",
        Response: "True",
        rating: 9,
        notes: "my favourite series!",
        date: daysAgo(11),
      },
      {
        Title: "Indiana Jones and the Kingdom of the Crystal Skull",
        Year: "2008",
        Rated: "PG-13",
        Released: "22 May 2008",
        Runtime: "122 min",
        Genre: "Action, Adventure",
        Director: "Steven Spielberg",
        Writer: "David Koepp, George Lucas, Jeff Nathanson",
        Actors: "Harrison Ford, Cate Blanchett, Shia LaBeouf",
        Plot: "In 1957, Indiana Jones is called back into action when he becomes entangled in a Soviet plot to uncover the secret behind mysterious artifacts known as the Crystal Skulls.",
        Language: "English, German, Russian",
        Country: "United States",
        Awards: "Nominated for 1 BAFTA Award10 wins & 42 nominations total",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BYTFiMDk2NzItZDU5Ni00ZjBjLTkzYWQtYzcwZDIwMWZjMmZiXkEyXkFqcGc@._V1_SX300.jpg",
        Ratings: [
          { Source: "Internet Movie Database", Value: "6.2/10" },
          { Source: "Rotten Tomatoes", Value: "77%" },
          { Source: "Metacritic", Value: "65/100" },
        ],
        Metascore: "65",
        imdbRating: "6.2",
        imdbVotes: "506,461",
        imdbID: "tt0367882",
        Type: "movie",
        DVD: "N/A",
        BoxOffice: "$317,101,119",
        Production: "N/A",
        Website: "N/A",
        Response: "True",
        rating: 7,
        notes: "",
        date: daysAgo(2),
      },
      {
        Title: "Breaking Bad",
        Year: "2008–2013",
        Rated: "TV-MA",
        Released: "20 Jan 2008",
        Runtime: "49 min",
        Genre: "Crime, Drama, Thriller",
        Director: "N/A",
        Writer: "Vince Gilligan",
        Actors: "Bryan Cranston, Aaron Paul, Anna Gunn",
        Plot: "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student to secure his family's future.",
        Language: "English, Spanish",
        Country: "United States",
        Awards: "Won 16 Primetime Emmys. 169 wins & 269 nominations total",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BMzU5ZGYzNmQtMTdhYy00OGRiLTg0NmQtYjVjNzliZTg1ZGE4XkEyXkFqcGc@._V1_SX300.jpg",
        Ratings: [
          { Source: "Internet Movie Database", Value: "9.5/10" },
          { Source: "Rotten Tomatoes", Value: "96%" },
        ],
        Metascore: "N/A",
        imdbRating: "9.5",
        imdbVotes: "2,409,035",
        imdbID: "tt0903747",
        Type: "series",
        totalSeasons: "5",
        Response: "True",
        rating: 9,
        notes: "i loved the character development!",
        date: daysAgo(0),
      },
    ],
    watchlist: [
      {
        Title: "The Dark Knight",
        Year: "2008",
        Rated: "PG-13",
        Released: "18 Jul 2008",
        Runtime: "152 min",
        Genre: "Action, Crime, Drama",
        Director: "Christopher Nolan",
        Writer: "Jonathan Nolan, Christopher Nolan, David S. Goyer",
        Actors: "Christian Bale, Heath Ledger, Aaron Eckhart",
        Plot: "When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.",
        Language: "English, Mandarin",
        Country: "United States, United Kingdom",
        Awards: "Won 2 Oscars. 163 wins & 165 nominations total",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
        Ratings: [
          { Source: "Internet Movie Database", Value: "9.1/10" },
          { Source: "Rotten Tomatoes", Value: "94%" },
          { Source: "Metacritic", Value: "85/100" },
        ],
        Metascore: "85",
        imdbRating: "9.1",
        imdbVotes: "3,087,450",
        imdbID: "tt0468569",
        Type: "movie",
        DVD: "N/A",
        BoxOffice: "$534,987,076",
        Production: "N/A",
        Website: "N/A",
        Response: "True",
      },
      {
        Title: "Fast & Furious 6",
        Year: "2013",
        Rated: "PG-13",
        Released: "24 May 2013",
        Runtime: "130 min",
        Genre: "Action, Thriller",
        Director: "Justin Lin",
        Writer: "Chris Morgan, Gary Scott Thompson",
        Actors: "Vin Diesel, Paul Walker, Dwayne Johnson",
        Plot: "Hobbs has Dominic and Brian reassemble their crew to take down a team of mercenaries, but Dominic unexpectedly gets sidetracked with facing his presumed deceased girlfriend, Letty.",
        Language: "English, Spanish, Russian, Japanese, Cantonese, Dutch, Danish, Ukrainian",
        Country: "Japan, United States",
        Awards: "12 wins & 22 nominations total",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BMTM3NTg2NDQzOF5BMl5BanBnXkFtZTcwNjc2NzQzOQ@@._V1_SX300.jpg",
        Ratings: [
          { Source: "Internet Movie Database", Value: "7.0/10" },
          { Source: "Rotten Tomatoes", Value: "71%" },
          { Source: "Metacritic", Value: "61/100" },
        ],
        Metascore: "61",
        imdbRating: "7.0",
        imdbVotes: "433,483",
        imdbID: "tt1905041",
        Type: "movie",
        DVD: "N/A",
        BoxOffice: "$238,679,850",
        Production: "N/A",
        Website: "N/A",
        Response: "True",
      },
      {
        Title: "Dexter: Original Sin",
        Year: "2024–2025",
        Rated: "TV-MA",
        Released: "13 Dec 2024",
        Runtime: "N/A",
        Genre: "Crime, Drama, Mystery",
        Director: "N/A",
        Writer: "Clyde Phillips",
        Actors: "Patrick Gibson, Christian Slater, Molly Brown",
        Plot: "A young Dexter Morgan transitions into an avenging serial killer.",
        Language: "English",
        Country: "United States",
        Awards: "N/A",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BYTVlZjNhYjktMWYyNy00MmYyLTk3ZjctMDQwMWIwYjdkODc3XkEyXkFqcGc@._V1_SX300.jpg",
        Ratings: [{ Source: "Internet Movie Database", Value: "8.2/10" }],
        Metascore: "N/A",
        imdbRating: "8.2",
        imdbVotes: "54,473",
        imdbID: "tt32252772",
        Type: "series",
        totalSeasons: "1",
        Response: "True",
      },
      {
        Title: "The Hobbit: The Desolation of Smaug",
        Year: "2013",
        Rated: "PG-13",
        Released: "13 Dec 2013",
        Runtime: "161 min",
        Genre: "Adventure, Fantasy",
        Director: "Peter Jackson",
        Writer: "Fran Walsh, Philippa Boyens, Peter Jackson",
        Actors: "Ian McKellen, Martin Freeman, Richard Armitage",
        Plot: "The dwarves, along with Bilbo Baggins and Gandalf the Grey, continue their quest to reclaim the Lonely Mountain, their homeland, from the dragon Smaug.",
        Language: "English",
        Country: "New Zealand, United States",
        Awards: "Nominated for 3 Oscars. 19 wins & 90 nominations total",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BMzU0NDY0NDEzNV5BMl5BanBnXkFtZTgwOTIxNDU1MDE@._V1_SX300.jpg",
        Ratings: [
          { Source: "Internet Movie Database", Value: "7.8/10" },
          { Source: "Rotten Tomatoes", Value: "74%" },
          { Source: "Metacritic", Value: "66/100" },
        ],
        Metascore: "66",
        imdbRating: "7.8",
        imdbVotes: "741,669",
        imdbID: "tt1170358",
        Type: "movie",
        DVD: "N/A",
        BoxOffice: "$258,387,334",
        Production: "N/A",
        Website: "N/A",
        Response: "True",
      },
    ],
  },
};

export default initialState;
